blank_issues_enabled: false
contact_links:
  - name: Official channels Chameleon Ultra Community
    url: https://github.com/RfidResearchGroup/ChameleonUltra#official-channels
    about: Got questions? Ask in *official channels*, not in an issue
